### ISSUE TITLE
JS errors : calling native console.log() failed

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#482]
Hi,

Phantomas generates many errors when running on this page: http://www.lafermeduweb.net
The errors seems to be internal, but i've been struggling for 2 hours looking for the reason.

Here is a part of the log in verbose mode:
```
15:49:52.925 JS error: Error: phantomas: calling native console.log() failed ("TypeError: '["DOMqueriesByTagName","%s (in %s)","head","#document"]' is not a valid argument for 'Function.prototype.apply' (evaluating 'this.addOffender.apply')")!
15:49:52.925 Event jserror emitted
15:49:52.925 Error: phantomas: calling native console.log() failed ("TypeError: '["DOMqueriesByTagName","%s (in %s)","head","#document"]' is not a valid argument for 'Function.prototype.apply' (evaluating 'this.addOffender.apply')")!
15:49:52.926 Backtrace: sendMsg(): /Users/gaelmetais/Documents/GitHub/phantomas/core/scope.js @ 127 / addOffender(): /Users/gaelmetais/Documents/GitHub/phantomas/core/scope.js @ 157 / selectorTagNameSpy(): phantomjs://webpage.evaluate() @ 35 / unknown fn: /Users/gaelmetais/Documents/GitHub/phantomas/core/scope.js @ 210 / unknown fn: http://static.lafermeduweb.net/js/fdw-min.js @ 1 / unknown fn: http://static.lafermeduweb.net/js/fdw-min.js @ 1
```

Any idea why it is failing?

**Comment by gmetais** [comment]
I managed to understand the problem. It's when a website (or a JS library) overrides some JSON related functions.

- Mootools 1.2 overrides the `window.JSON` object, `JSON.stringify` and `JSON.parse` don't exist anymore. It's fine in scope.js because the stringify method [is saved](https://github.com/macbre/phantomas/blob/devel/core/scope.js#L94). But it's not in some other modules ([example](https://github.com/macbre/phantomas/blob/devel/modules/globalVariables/globalVariables.js#L56)).

- Prototype 1.6 (and Mootools 1.2 too) creates an `Array.prototype.toJSON` function which get used by JSON.stringify ([stackoverflow](http://stackoverflow.com/questions/710586/json-stringify-array-bizarreness-with-prototype-js)).

These problems got fixed in later releases.

Some example websites: 
www.lafermeduweb.net uses Mootools 1.2.0 
www.ratp.fr uses Prototype 1.6.1

Not an easy bug to fix. Maybe the cleanest way would be to add some `Phantomas.JSONstringify` and `Phantomas.JSONparse` functions which do not rely on `Array/Object/Hash/String.prototype.toJSON`.

**Comment by macbre** [comment]
@gmetais, thanks for investigating.

phantomas already copies the native `console.log` before site JS can modify it. The simple fix here is to do the same for JSON related functions.

**Comment by gmetais** [comment]
Be careful, there will still be a problem with:
```js
Array.prototype.toJSON
Object.prototype.toJSON
Hash.prototype.toJSON
String.prototype.toJSON
```

By default, they don't exist in the browser. But the `JSON.stringify` function will look for them and use them if they get defined.

That's the touchy part of this fix.

**Comment by macbre** [comment]
`Error: phantomas: calling native console.log() failed` fixed in a9b5a9d.

However, there's still `TypeError: 'undefined' is not a function (evaluating 'JSON.parse("{\"svgResources\":[]}")')` caused by `JSON.parse` being removed.

**Comment by gmetais** [comment]
Awesome, thank you!

**Comment by gmetais** [comment]
For your information, this bug is still occurring on https://www.washingtonpost.com

For the moment I can't find the reason :(
